const params = {
	tubeOD: 20,
	tubeID: 16.7,
	stickout: 15,
	margin: 1.0,
	hollowDiameter: 12.5,
	pinHoleDiameter: 3.5,
	meltInsertLength: 5.7,
	meltInsertSupportWidth: 8,
	connectorToPipeMargin: 1.0,
	outsideResolution: 32,
	insideResolution: 16,
	textMargin: 1.5,
	textDepth: 0.5,
	textSize: 7.0,
}